"""Delete labour_wages table

Revision ID: 00059ad7fb05
Revises: 5d5e47975248
Create Date: 2024-03-15 13:18:18.229519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00059ad7fb05'
down_revision: Union[str, None] = '5d5e47975248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labour_wages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labour_wages',
    sa.Column('sl_no', sa.INTEGER(), nullable=False),
    sa.Column('emp_category', sa.VARCHAR(), nullable=True),
    sa.Column('wage', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('sl_no')
    )
    # ### end Alembic commands ###
