"""Delete ContractEmployee

Revision ID: 18af43bcdedf
Revises: 4851df8f93ba
Create Date: 2024-03-14 09:21:36.516374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18af43bcdedf'
down_revision: Union[str, None] = '4851df8f93ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract_employees')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_employees',
    sa.Column('emp_punch_id', sa.INTEGER(), nullable=False),
    sa.Column('emp_name', sa.VARCHAR(), nullable=True),
    sa.Column('contract_no', sa.VARCHAR(), nullable=True),
    sa.Column('esi_no', sa.INTEGER(), nullable=True),
    sa.Column('pf_no', sa.INTEGER(), nullable=True),
    sa.Column('bank_acc_no', sa.INTEGER(), nullable=True),
    sa.Column('date_of_joining', sa.DATE(), nullable=True),
    sa.Column('emp_category', sa.VARCHAR(), nullable=True),
    sa.Column('bank_acc_ifsc_code', sa.VARCHAR(), nullable=True),
    sa.CheckConstraint('emp_category IN ("skilled","semi-sklled","unskilled")'),
    sa.ForeignKeyConstraint(['contract_no'], ['contracts.contract_no'], ),
    sa.PrimaryKeyConstraint('emp_punch_id')
    )
    # ### end Alembic commands ###
