"""Add ContractBills table

Revision ID: 1a8f66a1f0a3
Revises: e2675e8a93db
Create Date: 2024-03-15 13:20:59.867309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a8f66a1f0a3'
down_revision: Union[str, None] = 'e2675e8a93db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('ge_no', sa.Integer(), nullable=False),
    sa.Column('contract_no', sa.String(), nullable=True),
    sa.Column('rar_no', sa.Integer(), nullable=True),
    sa.Column('invoice_no', sa.String(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('invoice_amount', sa.Integer(), nullable=True),
    sa.Column('ge_date', sa.Date(), nullable=True),
    sa.Column('rr_no', sa.String(), nullable=True),
    sa.Column('penalty', sa.Integer(), nullable=True),
    sa.Column('abstract_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_no'], ['contracts.contract_no'], ),
    sa.PrimaryKeyConstraint('ge_no'),
    sa.UniqueConstraint('invoice_no'),
    sa.UniqueConstraint('rr_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bills')
    # ### end Alembic commands ###
