"""Add  ManpowerWage

Revision ID: 274564772d56
Revises: 367895bf20cb
Create Date: 2024-03-15 14:04:32.681891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '274564772d56'
down_revision: Union[str, None] = '367895bf20cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labour_wages',
    sa.Column('emp_category', sa.String(), nullable=False),
    sa.Column('wage', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.CheckConstraint("emp_category IN ('skilled','semi-skilled','unskilled')"),
    sa.PrimaryKeyConstraint('emp_category')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labour_wages')
    # ### end Alembic commands ###
