"""Delete  ManpowerWage

Revision ID: 367895bf20cb
Revises: 1a8f66a1f0a3
Create Date: 2024-03-15 13:59:49.128173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '367895bf20cb'
down_revision: Union[str, None] = '1a8f66a1f0a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labour_wages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labour_wages',
    sa.Column('sl_no', sa.INTEGER(), nullable=False),
    sa.Column('emp_category', sa.VARCHAR(), nullable=True),
    sa.Column('wage', sa.NUMERIC(precision=6, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('sl_no')
    )
    # ### end Alembic commands ###
