"""Updated emp_category constraint in ContractEmployee

Revision ID: 4851df8f93ba
Revises: 7fbe19a1c1f4
Create Date: 2024-03-14 09:09:08.095901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4851df8f93ba'
down_revision: Union[str, None] = '7fbe19a1c1f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
