"""Delete ContractBills table

Revision ID: 633f114ec677
Revises: 84fcbc38f23a
Create Date: 2024-03-15 13:17:13.488811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '633f114ec677'
down_revision: Union[str, None] = '84fcbc38f23a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bills')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('contract_no', sa.VARCHAR(), nullable=True),
    sa.Column('rar_no', sa.INTEGER(), nullable=True),
    sa.Column('invoice_no', sa.VARCHAR(), nullable=True),
    sa.Column('invoice_date', sa.DATE(), nullable=True),
    sa.Column('invoice_amount', sa.INTEGER(), nullable=True),
    sa.Column('ge_date', sa.DATE(), nullable=True),
    sa.Column('ge_no', sa.INTEGER(), nullable=True),
    sa.Column('rr_no', sa.VARCHAR(), nullable=True),
    sa.Column('penalty', sa.INTEGER(), nullable=True),
    sa.Column('abstract_timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['contract_no'], ['contracts.contract_no'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ge_no'),
    sa.UniqueConstraint('invoice_no'),
    sa.UniqueConstraint('rr_no')
    )
    # ### end Alembic commands ###
