"""Initial Migration

Revision ID: d913c8032cf8
Revises: 
Create Date: 2024-03-18 07:54:15.659336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd913c8032cf8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('eic_dept_no', sa.String(), nullable=False,server_default=" "))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'eic_dept_no')
    # ### end Alembic commands ###
