"""Add labour_wages table

Revision ID: e2675e8a93db
Revises: 00059ad7fb05
Create Date: 2024-03-15 13:18:54.534591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2675e8a93db'
down_revision: Union[str, None] = '00059ad7fb05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labour_wages',
    sa.Column('sl_no', sa.Integer(), nullable=False),
    sa.Column('emp_category', sa.String(), nullable=True),
    sa.Column('wage', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('sl_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labour_wages')
    # ### end Alembic commands ###
