"""updated ContractBills

Revision ID: 063d992e69b4
Revises: aa97ddf5507d
Create Date: 2024-04-06 20:35:49.396102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '063d992e69b4'
down_revision: Union[str, None] = 'aa97ddf5507d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'invoice_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('invoice_amount', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
