"""ContractNew table added

Revision ID: 197f68dc271f
Revises: 83c788e0f6c5
Create Date: 2024-03-23 11:47:38.573743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '197f68dc271f'
down_revision: Union[str, None] = '83c788e0f6c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contracts_new')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts_new',
    sa.Column('contract_no', sa.VARCHAR(), nullable=False),
    sa.Column('eic_pbno', sa.VARCHAR(), nullable=True),
    sa.Column('oic_pbno', sa.VARCHAR(), nullable=True),
    sa.Column('contract_type', sa.VARCHAR(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('duration_months', sa.INTEGER(), nullable=True),
    sa.Column('bill_frequency', sa.INTEGER(), nullable=True),
    sa.Column('contract_value', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('contract_description', sa.VARCHAR(), nullable=False),
    sa.Column('vendor_id', sa.VARCHAR(), nullable=False),
    sa.Column('vendor_name', sa.VARCHAR(), nullable=False),
    sa.Column('vendor_address', sa.VARCHAR(), nullable=False),
    sa.Column('vendor_gst', sa.VARCHAR(), nullable=False),
    sa.Column('eic_dept_no', sa.VARCHAR(), nullable=False),
    sa.Column('work_order_no', sa.VARCHAR(), nullable=False),
    sa.Column('gem_contract_no', sa.VARCHAR(), nullable=False),
    sa.CheckConstraint("contract_type IN ('manpower', 'work_package')"),
    sa.ForeignKeyConstraint(['eic_dept_no'], ['department.dept_no'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.vendor_id'], ),
    sa.PrimaryKeyConstraint('contract_no'),
    sa.UniqueConstraint('contract_no')
    )
    # ### end Alembic commands ###
