"""aadhaar_no added in ContractEmployee

Revision ID: 738cb31bbb58
Revises: 005b38dfd067
Create Date: 2024-04-16 19:01:45.674954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '738cb31bbb58'
down_revision: Union[str, None] = '005b38dfd067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_employees', sa.Column('aadhaar_no', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract_employees', 'aadhaar_no')
    # ### end Alembic commands ###
