"""vendors table added

Revision ID: 83c788e0f6c5
Revises: 2ae0309ae73e
Create Date: 2024-03-23 11:36:26.151627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83c788e0f6c5'
down_revision: Union[str, None] = '2ae0309ae73e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('vendor_epf_code', sa.String(), nullable=False),
    sa.Column('vendor_esi_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('vendor_id')
    )
    op.create_table('contracts_new',
    sa.Column('contract_no', sa.String(), nullable=False),
    sa.Column('eic_pbno', sa.String(), nullable=True),
    sa.Column('oic_pbno', sa.String(), nullable=True),
    sa.Column('contract_type', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('bill_frequency', sa.Integer(), nullable=True),
    sa.Column('contract_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('contract_description', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('vendor_name', sa.String(), nullable=False),
    sa.Column('vendor_address', sa.String(), nullable=False),
    sa.Column('vendor_gst', sa.String(), nullable=False),
    sa.Column('eic_dept_no', sa.String(), nullable=False),
    sa.Column('work_order_no', sa.String(), nullable=False),
    sa.Column('gem_contract_no', sa.String(), nullable=False),
    sa.CheckConstraint("contract_type IN ('manpower', 'work_package')"),
    sa.ForeignKeyConstraint(['eic_dept_no'], ['department.dept_no'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.vendor_id'], ),
    sa.PrimaryKeyConstraint('contract_no'),
    sa.UniqueConstraint('contract_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contracts_new')
    op.drop_table('vendors')
    # ### end Alembic commands ###
