"""from_date and to_date added in bills table

Revision ID: 85f1be2ee594
Revises: c8b94121e2ed
Create Date: 2024-03-31 07:59:11.316297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85f1be2ee594'
down_revision: Union[str, None] = 'c8b94121e2ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('from_date', sa.Date(), nullable=True))
    op.add_column('bills', sa.Column('to_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'to_date')
    op.drop_column('bills', 'from_date')
    # ### end Alembic commands ###
