"""created  ContractBills

Revision ID: aa97ddf5507d
Revises: e108caaccb1f
Create Date: 2024-04-06 20:33:48.575218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa97ddf5507d'
down_revision: Union[str, None] = 'e108caaccb1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('ge_no', sa.Integer(), nullable=True),
    sa.Column('contract_no', sa.String(), nullable=False),
    sa.Column('rar_no', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('invoice_amount', sa.Integer(), nullable=True),
    sa.Column('ge_date', sa.Date(), nullable=True),
    sa.Column('rr_no', sa.String(), nullable=True),
    sa.Column('penalty', sa.Float(), nullable=True),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('bill_timestamp', sa.DateTime(), nullable=True),
    sa.Column('bill_payment_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['contract_no'], ['contracts.contract_no'], ),
    sa.PrimaryKeyConstraint('contract_no', 'rar_no'),
    sa.UniqueConstraint('ge_no'),
    sa.UniqueConstraint('invoice_no'),
    sa.UniqueConstraint('rr_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bills')
    # ### end Alembic commands ###
