"""vendor_id dropped from contracts

Revision ID: c662334a3525
Revises: 197f68dc271f
Create Date: 2024-03-23 11:49:27.672250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c662334a3525'
down_revision: Union[str, None] = '197f68dc271f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'vendor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('vendor_id', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
