"""bills_boq_lines table added

Revision ID: c8b94121e2ed
Revises: 8428a48f4b5e
Create Date: 2024-03-30 22:31:12.947554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8b94121e2ed'
down_revision: Union[str, None] = '8428a48f4b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills_boq_lines',
    sa.Column('contract_no', sa.String(), nullable=False),
    sa.Column('boq_line_no', sa.Integer(), nullable=False),
    sa.Column('rar_no', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['boq_line_no'], ['bill_of_quantities.sl_no'], ),
    sa.ForeignKeyConstraint(['contract_no'], ['contracts.contract_no'], ),
    sa.PrimaryKeyConstraint('contract_no', 'boq_line_no', 'rar_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bills_boq_lines')
    # ### end Alembic commands ###
