"""aadhaar_no added in ContractEmployee

Revision ID: ca19724d1465
Revises: 738cb31bbb58
Create Date: 2024-04-16 19:03:39.011309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca19724d1465'
down_revision: Union[str, None] = '738cb31bbb58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
